version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - session:/sessions
  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: mailchat
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
volumes:
  db_data:
  session:
